ACCESS_KEY: ''
BUCKET: 'Videos'
MOVEMENT_MESSAGE: There has been movement detected in your home.
MOVEMENT_SUBJECT: Movement Detected
PASSWORD: ''
PORT: 587
RECEIVER_EMAIL: your_email@mail.fresnostate.edu
RECORDING_MESSAGE: A recording of the detected movement has been uploaded to your Amazon AWS S3 folder.
RECORDING_SUBJECT: Recording Has Been Uploaded
SECRET_KEY: ''
SENDER_EMAIL: no-reply@homesecuritypi.com
SMTP_SERVER: smtp.gmail.com
USERNAME: 'your_email@mail.fresnostate.edu'
